'use strict';

// tests for employeeLeave
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('employeeLeave', '/handler.js', 'employeeLeave');

describe('employeeLeave', () => {
  before((done) => {
    done();
  });

  it('should response without an error', () => {
    return wrapped.run({pathParameters: {id: '5d63b7f31ee37200084666e6'}}).then((response) => {
      expect(response).to.haveOwnProperty('statusCode');
      expect(response.statusCode).to.equal(400);
      expect(response).to.haveOwnProperty('body');
    });
  });
});
