'use strict';

// tests for employeeFindAll
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('employeeFindAll', '/handler.js', 'employeeFindAll');

describe('employeeFindAll', () => {
  before((done) => {
    done();
  });

  it('should return without an error', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.haveOwnProperty('statusCode');
      expect(response).to.haveOwnProperty('body');
    });
  });
});
