'use strict';

// tests for employeeFindById
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('employeeFindById', '/handler.js', 'employeeFindById');

describe('employeeFindById', () => {
  before((done) => {
    done();
  });

  it('should return without an error', () => {
    return wrapped.run({pathParameters: {id: '5d63b7f31ee37200084666e6'}}).then((response) => {
      expect(response).to.haveOwnProperty('statusCode');
      expect(response).to.haveOwnProperty('body');
    });
  });
});
