'use strict';

// tests for employeeSignIn
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('employeeSignIn', '/handler.js', 'employeeSignIn');

describe('employeeSignIn', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({body: {email: 'ibe@mail.com', password: 'qwerqwer'}}).then((response) => {
      expect(response).to.haveOwnProperty('statusCode');
      expect(response).to.haveOwnProperty('body');
    });
  });
});
