'use strict';

// tests for getWeekly
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getWeekly', '/handler.js', 'getWeekly');

describe('getWeekly', () => {
  before((done) => {
    done();
  });

  it('should response without an error', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.haveOwnProperty('statusCode');
      expect(response).to.haveOwnProperty('body');
    });
  });
});
